version: 2
updates:
  - package-ecosystem: npm
    directories:
      - /
      - packages/app
      - packages/backend
      - packages/builder
      - packages/shared
    schedule:
      interval: weekly
    versioning-strategy: increase
    groups:
      deps:
        patterns:
          - '*'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      workflows:
        patterns:
          - '*'
