version: 1
name: Swagger
blip:
  - version: "2.6"
    ring: ADOPT
description: |
  The OpenAPI Specification, originally known as the [Swagger](https://swagger.io/) Specification,
  is a specification for machine-readable interface files for describing, producing,
  consuming, and visualizing RESTful web services.
rationale:
  Enables both QA, developers and external consultants to easily view and test our API's,
  it also gives valuable documentation about expected input and output including its valuetypes.
  It also supports OAuth so the testing is done with a valid token.
