name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./.scripts/python_requirements.txt
    - name: Yaml Lint
      run: python .scripts/yaml_lint.py
    - name: Verify schema
      run: python .scripts/yaml_validate.py
