name: Debug
on: pull_request

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout infra repository
        uses: actions/checkout@v2

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
