name: Workflow

on: [push]

jobs:
  yamllint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./.scripts/python_requirements.txt
    - name: Yaml Lint
      run: python .scripts/yaml_lint.py
    - name: Verify schema
      run: python .scripts/yaml_validate.py

  build:

      needs: yamllint

      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: NPM Install
        run: npm ci
      - name: Lint javascript
        run: |
            npm run lint:js -- \
              --format junit \
              --output-file test-results/eslint/TEST-eslint.xml
      - name: Unit tests
        run: npm test -- --ci --runInBand --coverage
      - name: Build radar
        run: npm run build
      - name: Build Docker image
        run: docker build -t extenda/tech-radar:GITHUB_SHA .
